- package-lock.json
- packages/smartcontracts/hardhat.config.ts
- packages/smartcontracts/package.json
Integrated following these instructions, worked fine to verify the DelegatedAccessRegistry's code:
https://coinsbench.com/verify-smart-contract-on-polygonscan-using-hardhat-9b8331dbd888
> [FRONT-1045] Verify contracts on Polygonscan with an NPM command

- packages/smartcontracts/contracts/GatedChatRooms/ERC1155JoinPolicy.sol
- packages/smartcontracts/contracts/GatedChatRooms/ERC20JoinPolicy.sol
- packages/smartcontracts/contracts/GatedChatRooms/ERC721JoinPolicy.sol
- packages/smartcontracts/contracts/GatedChatRooms/GatedJoinPolicy.sol
- packages/smartcontracts/contracts/GatedChatRooms/JoinPolicyFactory.sol
- packages/smartcontracts/hardhat.config.ts
- packages/smartcontracts/scripts/deployToLivenet/4_deployJoinPolicyFactory.ts
- packages/smartcontracts/test/GatedChatRooms/ERC1155JoinPolicy.test.ts
- packages/smartcontracts/test/GatedChatRooms/ERC20JoinPolicy.test.ts
- packages/smartcontracts/test/GatedChatRooms/ERC721JoinPolicy.test.ts
- packages/smartcontracts/test/GatedChatRooms/JoinPolicyFactory.test.ts
Reworked the indexing of registered policies in the factory as there was a chance of overlap.
> Implementation modifications for NFT-gated chatrooms

- packages/docker-dev-chain-init/smartContractInit.log
- packages/hub-contracts/contracts/ProjectRegistry/IProjectRegistry.sol
- packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol
- packages/hub-contracts/scripts/interactProjectRegistry.ts
- packages/hub-contracts/test/contracts/MarketplaceV4.test.ts
- packages/hub-contracts/test/contracts/ProjectRegistry.test.ts
- packages/hub-contracts/test/contracts/ProjectStakingV1.test.ts
- packages/hub-contracts/test/contracts/Uniswap2Adapter.test.ts
- packages/hub-subgraph/src/projectRegistry.ts
- packages/hub-subgraph/subgraph.yaml
- packages/hub-subgraph/tests/helpers/mocked-event.ts
- packages/hub-subgraph/tests/projectRegistry.test.ts
createProject: provide an array of streamIds as an argument so that we can create the whole project with only 1 tx
updateProject: Array of streamIds added as well. This should handle both addition and removal of streams.
> ETH-432 ProjectRegistry improvements

- packages/docker-dev-chain-init/index.js
- packages/docker-dev-chain-init/smartContractInit.log
- packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol
- packages/hub-contracts/hardhat.config.ts
- packages/hub-contracts/scripts/interactMarketplaceV3.ts
- packages/hub-contracts/scripts/interactProjectRegistry.ts
- packages/hub-contracts/test/contracts/MarketplaceV4.test.ts
- packages/hub-contracts/test/contracts/ProjectRegistry.test.ts
- packages/hub-contracts/test/contracts/Uniswap2Adapter.test.ts
ProjectRegistry has the trusted role in StreamRegistry and can use the trusted functions
> ETH-443 - automatically grant permission to streams from project registry

- packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/AdminKickPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/DefaultLeavePolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/IKickPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
- packages/network-contracts/test/hardhat/BrokerEconomics/Bounty.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/AdminKickPolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/DefaultLeavePolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
ended up refactoring reduceStake and AdminKickPolicy quite a bit, but now that calculations should match tests again...
> Prevent unstaking/leaving when there's committed stake

- packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
- packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
- packages/network-contracts/contracts/BrokerEconomics/BrokerPoolFactory.sol
- packages/network-contracts/test/hardhat-slow-tests/BrokerPool.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/Bounty.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/AdminKickPolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/DefaultLeavePolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/StakeWeightedAllocationPolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BrokerPool.test.ts
reduce by -> reduce to, i.e. reduceStake() => reduceStakeTo()
> Renamings based on team meeting 2023-03-01

- packages/network-contracts/.solhint.json
- packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/AdminKickPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/BrokerPoolOnlyJoinPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/DefaultLeavePolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/IKickPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
- packages/network-contracts/contracts/BrokerEconomics/IBroker.sol
- packages/network-contracts/contracts/BrokerEconomics/ISlashListener.sol
- packages/network-contracts/contracts/BrokerEconomics/StreamrConstants.sol
- packages/network-contracts/contracts/BrokerEconomics/testcontracts/TestKickPolicy.sol
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
- packages/network-contracts/test/hardhat/BrokerEconomics/BrokerPool.test.ts
This is on top of ETH-459, please merge that first!
also:
- separated onKick and onSlash while debugging unstaking
- added test for when target forceUnstakes
> ETH-466: Remove cancelFlag

- packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
- packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
- packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
- packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
tests actually became nicer to look at! Who knew, a good sign!
> ETH-470 ReviewRequest moved from Bounty to BrokerPool

- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipFactory.sol
- packages/network-contracts/package.json
- packages/network-contracts/scripts/tatum/2_deployNewSponsorship.ts
- packages/network-contracts/scripts/tatum/4_deployNewOperator.ts
- packages/network-contracts/scripts/tatum/allinoneHardhat.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/operator.ts
- packages/network-subgraphs/src/operatorFactory.ts
- packages/network-subgraphs/src/sponsorship.ts
- packages/network-subgraphs/src/sponsorshipFactory.ts
- packages/network-subgraphs/subgraph.yaml
Added more eventhandlers, more values to some events and fixed the actual eventhandling.
Some values are still not being filled in the OperatorDailyBuckets!
> Fix subgraphs

- packages/network-contracts/contracts/OperatorTokenomics/IOperator.sol
- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts
also stake top-up from Operator was broken and tests weren't catching it for some reason, so added a test
> ETH-512 fix: show Profit/Loss after kicking

- packages/config/src/networks.json
Make the Polygon RPCs in the config package the same as the defaults in StreamrClient
> Update Polygon RPCs in config

- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultPoolYieldPolicy.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
ticket: https://linear.app/streamr/issue/ETH-535/poolvalue-update-mechanism-should-pull-earnings-into-operatorcontract
> Eth 535 pull earnings into operator contract

- .vscode/launch.json
- packages/network-contracts/README.md
- packages/network-contracts/package.json
- packages/network-contracts/scripts/tatum/streamrEnvDeployer.ts
- packages/network-contracts/src/StreamrEnvDeployer.ts
- packages/network-contracts/src/exports.ts
it needs to be published once merged
> made network-contracts package smaller from 1.1mb to 360kb

- package-lock.json
- packages/hub-contracts/package.json
- packages/network-contracts/package.json
- packages/network-contracts/test/integration/ens-e2e.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/sponsorship.ts
- packages/network-subgraphs/src/sponsorshipFactory.ts
Also ProjectedInsolvencyUpdate
> ETH-560: fix SponsorshipUpdated event handling

- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/operator.ts
https://linear.app/streamr/issue/ETH-564/add-operatorsetoperatorscutfraction
> Eth 564 update operators cut fraction

- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
Part of: cleaning up Operator tests
Did not change them, just moved around
> Sorted operator tests under describe blocks

- .vscode/launch.json
- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorFactory.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/INodeModule.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/IQueueModule.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/IStakeModule.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/NodeModule.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/QueueModule.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
- packages/network-contracts/package.json
- packages/network-contracts/src/StreamrEnvDeployer.ts
- packages/network-contracts/src/exports.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/OperatorContractOnlyJoinPolicy.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/deployTestContracts.ts
pulled Operator logic into 3 modules,
changed all error messages to error types
> Modularize operator

- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/DefaultLeavePolicy.sol
- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
- packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/DefaultLeavePolicy.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts
Add slashingFraction to StreamrConfig
Change math for setting the flag stake
Update commnens in contracts and tests
> feat: make slashing fraction configurable

- package-lock.json
- packages/network-contracts/package.json
Runs only the OperatorTokenomics files
> Downgrade hardhat to the last version before the Shanghai/Shapella hardfork

- packages/config/src/index.ts
- packages/network-contracts/src/StreamrEnvDeployer.ts
> fix: update renamed policy

- packages/config/src/index.ts
Add DHT entry point definitions for `mumbai` and `dev2` networks.
> config: add `entryPoints`

- packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.sol
- packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestAllocationPolicy.sol
- packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestKickPolicy.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts
> Eth 588 testcoverage

- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts
sponsorship factory path coverage 100%, missing from 100% line coverge are 2 unreachable internal functions
> sponsorship factory path coverage

- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultDelegationPolicy.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
Second iteration of "making operator pay for slashings"
> ETH-614: pay for slashing by burning operator's self-delegation

- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
Only  `_msgData()` remained to be covered
> Operator further coverage

- packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
- packages/network-contracts/contracts/OperatorTokenomics/OperatorFactory.sol
- packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipFactory.sol
- packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
- packages/network-contracts/src/StreamrEnvDeployer.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/OperatorFactory.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/StreamrConfig.test.ts
- packages/network-contracts/test/hardhat/OperatorTokenomics/deployTestContracts.ts
UUPS:
- StreamrConfig
- OperatorFactory
- SponsorshipFactory
Also added updateTemplate(s) for the admin to the factories. This completes our upgradeability story for 1.0.
> ETH-627: upgradeability

- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipFactory.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts
implement a test that was a TODO in the code
> ETH-638: Short policies arrays test in SponsorshipFactory

- packages/network-subgraphs/src/sponsorshipFactory.ts
toString()ing an address gives a runtime warning for invalid UTF-8
> subgraph fix: toHexString an address array

- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultExchangeRatePolicy.sol
it might even incur an internal transaction / call
> Remove unnecessary this

- packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultExchangeRatePolicy.sol
- packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
also fix Operator.test.ts to work with real StreamrConfig values
> ETH-691: minimum delegation test

- packages/config/src/index.ts
The frontend is using the `name` fields, so make them more human-readable. The name of the native coin on each chain is also needed.
@samt1803 if you're happy with the changes, could you please merge the changes and publish a new config version for the frontend?
> Name polish + add nativeCoinName

- packages/network-subgraphs/src/operator.ts
Clarify [ticket questions](https://linear.app/streamr/issue/ETH-677/total-value-charts-resolving-to-incorrect-values) before review
> ETH-677 Total value charts resolving to incorrect values

- packages/network-contracts/selectors.txt
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/operator.ts
delegatorDailybucket cumumativeEarningsWei fixed
> ETH-707 fix: reworked delegation values

- packages/expired-flag-closer/package-lock.json
- packages/expired-flag-closer/package.json
- packages/expired-flag-closer/src/flagCloser.ts
- packages/expired-flag-closer/tsconfig.build.json
- packages/expired-flag-closer/tsconfig.json
- packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
quick and dirty script to close expired flags, tested in dev-env and on mumbai
> ETH-699 flag closer

- packages/network-contracts/test/integration/contractsSubgraphSmoketest.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/operator.ts
- packages/network-subgraphs/src/operatorFactory.ts
- packages/network-subgraphs/src/sponsorship.ts
- packages/network-subgraphs/subgraph.yaml
- packages/network-subgraphs/subgraph_matic.yaml
- packages/network-subgraphs/subgraph_mumbai.yaml
> ETH-737: Operator.sol:version into subgraph as Operator.contractVersion

- packages/network-contracts/test/integration/contractsSubgraphSmoketest.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/operator.ts
- packages/network-subgraphs/subgraph.yaml
- packages/network-subgraphs/subgraph_matic.yaml
- packages/network-subgraphs/subgraph_mumbai.yaml
...not including the owner address itself
> ETH-753: add controllers to Operator entity

- packages/config/src/index.ts
- packages/network-contracts/src/StreamrEnvDeployer.ts
- packages/network-contracts/test/integration/contractsSubgraphSmoketest.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/operator.ts
- packages/network-subgraphs/subgraph.yaml
Turns out maybe controllers don't get indexed? Add better test
> ETH-753: add controller to smoke test

- packages/config/src/index.ts
- packages/dev-chain-fast/package.json
- packages/network-contracts/src/StreamrEnvDeployer.ts
- packages/network-contracts/test/integration/contractsSubgraphSmoketest.test.ts
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/.eslintrc.json
- packages/network-subgraphs/src/helpers.ts
- packages/network-subgraphs/src/operator.ts
- packages/network-subgraphs/subgraph.yaml
> ETH-761: Operator owner shouldn't have delegation.earliestUndelegationTimestamp

- packages/network-subgraphs/abis/StreamRegistry.json
- packages/network-subgraphs/schema.graphql
- packages/network-subgraphs/src/streamRegistry.ts
also updated ABI in subgraph package, though it doesn't make a difference (those methods aren't used in the subgraph)
> Also new-id StreamPermissions get userAddress if they're address-length

- packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
- packages/network-contracts/test/hardhat/Registries/StreamRegistry.test.ts
Includes also tests for upgrading v2->v3->v5 and refactored `StreamRegistry` test.
> ETH-792: public permissions can't be edit/grant/delete

- packages/dev-chain-fast/README.md
A section about troubleshooting compilation problems on a Mac with an ARM processor.
> docs(dev-chain-fast): Add troubleshooting section

- packages/config/config.json
Changed ports for these:
```
polygon-entrypoint-3.streamr.network
polygon-entrypoint-4.streamr.network
amoy-entrypoint-1.streamr.network
amoy-entrypoint-2.streamr.network
```
> Change entrypoint ports to 443

- packages/npm-network-contracts/build.sh
- packages/npm-network-contracts/hardhat.config.ts
- packages/npm-network-contracts/package-lock.json
- packages/npm-network-contracts/package.json
- packages/npm-network-contracts/src/exports.ts
Removed unnecessary exported ABIs, type definitions. Also removed SOL files.
Now only exports ABIs and type definitions which are needed in `sdk` and `node` packages.
Also added `package-lock.json`.
> feat(npm-network-contracts): Minimal API

- packages/npm-network-contracts/package-lock.json
- packages/npm-network-contracts/package.json
Add missing build dependencies. These were uncovered by deleting the top-level node_modules, so that imports don't accidentally find dependencies in the top-level.
> build(npm-network-contracts): add build dependencies

- packages/network-contracts/.openzeppelin/unknown-3338.json
- packages/network-contracts/doc/peaq_deployment.md
- packages/network-contracts/hardhat.config.ts
- packages/network-contracts/logs/2025-05-30-upgrade-peaq-streamregistry.txt
- packages/network-contracts/scripts/_read.ts
- packages/network-contracts/scripts/check.ts
- packages/network-contracts/scripts/checkers/check-StreamRegistry.ts
- packages/network-contracts/scripts/handOverAdminRolesTo.ts
- packages/network-contracts/scripts/setTrusted.ts
New scripts to probe the health of deployments.
Moved all admin roles to my new work address.
Did an upgrade to StreamRegistry in Peaq EVM chain.
Make the scripts more complete, also check ENS cache and tokenomics contracts
> feat(network-contracts): [ETH-874] Debugged the StreamRegistry deployment in Peaq EVM chain
