streamr-dev/network-contracts

packages/hub-subgraph/schema.graphql
packages/hub-subgraph/src/helpers.ts
packages/hub-subgraph/src/projectRegistry.ts
packages/hub-subgraph/tests/helpers/mocked-entity.ts
packages/hub-subgraph/tests/helpers/mocked-event.ts
packages/hub-subgraph/tests/projectRegistry.test.ts

Parse the project metadata and if "isDataUnion" field is found, set it's value in the subgraph entity. 
If it's not found, or the metadata is not a valid json, mark the project as non du.

feat: add isDataUnion flag to Project entity

---

packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/AdminKickPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/IAllocationPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/IKickPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/MinimumStakeJoinPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/StakeWeightedAllocationPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/testcontracts/TestAllocationPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/testcontracts/TestKickPolicy.sol
packages/network-contracts/test/hardhat/BrokerEconomics/Bounty.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/AdminKickPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/DefaultLeavePolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/StakeWeightedAllocationPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts

- don't call _slash if no leave penalty
- also implemented the +1/+2 votes idea to avoid ties (ETH-457)
- onStakeIncrease + onStakeDecrease => onStakeChange
- StakeUpdate event TODOs implemented (added tests into Bounty.test.ts)
- VoteKickPolicy now has review period and voting period (no "timeouts" except maybe if no one voted?)
- DRYed up some calculateAllocation overlaps in StakeWeightedAllocationPolicy

VoteKickPolicy timeline: first review period, then voting period

---

packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts

also VoteKickPolicy test cleanups
in smart contracts, uniformly `amountWei` instead of `amountTokenWei` or `amount`

ETH-458: even if flagger gets kicked before flag is resolved, now reviewers will get correctly paid

---

packages/network-subgraphs/README.md
packages/network-subgraphs/package.json

force docker to build subgraph deploy images in AMD64 platform instead of arm64 (on a apple silicon mac)

force docker to build subgraph deploy images in AMD64 platform

---

packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
packages/network-contracts/contracts/BrokerEconomics/BountyFactory.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/BrokerPoolOnlyJoinPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/DefaultLeavePolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/IAllocationPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/MaxAmountBrokersJoinPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/StakeWeightedAllocationPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
packages/network-contracts/contracts/BrokerEconomics/BrokerPoolFactory.sol
packages/network-contracts/contracts/BrokerEconomics/BrokerPoolPolicies/DefaultPoolYieldPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/StreamrConfig.sol
packages/network-contracts/contracts/BrokerEconomics/testcontracts/TestAllocationPolicy.sol
packages/network-contracts/scripts/tatum/1_deployBountyFactory.ts
packages/network-contracts/scripts/tatum/3_deployPoolContracts.ts
packages/network-contracts/test/hardhat/BrokerEconomics/Bounty.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/AdminKickPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/StakeWeightedAllocationPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BrokerPool.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/deployBounty.ts
packages/network-contracts/test/hardhat/Registries/ENScache.test.ts
packages/network-contracts/test/hardhat/Registries/StreamRegistry.test.ts

LocalStorage is still necessary, to avoid storage clashes for modules, since they would all be laid out in the same area by Solidity
gains/winnings/allocations → earnings
fix typo
removed StakeWeightedAllocationPolicy.getCumulativeWeiPerStake

ETH-435: renamings, removed GlobalStorage

---

packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
packages/network-contracts/contracts/BrokerEconomics/BrokerPoolFactory.sol
packages/network-contracts/contracts/BrokerEconomics/IBroker.sol
packages/network-contracts/contracts/BrokerEconomics/IBrokerPoolLivenessRegistry.sol
packages/network-contracts/contracts/BrokerEconomics/StreamrConfig.sol
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BrokerPool.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/setupBounty.ts

track "liveness" so that when unstaking from last Bounty, BrokerPool tells
a registry it's not live anymore
also tests modified so that now instead of "non-staked" brokers there's
several Bounties so the previously "non-staked" brokers are simply staked
in that other Bounty.

ETH-438: only select "live" BrokerPools as reviewers

---

packages/network-contracts/contracts/NodeRegistry/NodeRegistry.sol
packages/network-contracts/contracts/StreamStorageRegistry/StreamStorageRegistry.sol
packages/network-contracts/contracts/StreamStorageRegistry/StreamStorageRegistryV2.sol
packages/network-contracts/test/hardhat/BrokerEconomics/deployTestContracts.ts
packages/network-contracts/test/hardhat/Registries/StreamRegistry.test.ts
packages/network-contracts/test/hardhat/Registries/StreamStorageRegistry.test.ts
packages/network-contracts/test/hardhat/Registries/getEIP2771MetaTx.ts

I noticed while working on ETH-463 that StreamStorageRegistry.test.ts tests weren't run at all. The code had rot pretty bad. It runs now and all is green. I took most of it from StreamRegistry.test.ts which was being run; but ended up refactoring that too, to pull out the common EIP2771 stuff into a file (had been copy-pasted). Mopped it all up afterwards.
RegistryFromX isn't needed in StreamRegistry.test.ts for getters that don't look at msg.sender at all, it's just noise. Search+replaced those.
pulled EIP2771 meta tx generation to its own file (DRY)
also unified an error message between StreamRegistry and StreamStorageRegistry

Clean up registry tests

---

packages/network-contracts/contracts/BrokerEconomics/Bounty.sol
packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/StakeWeightedAllocationPolicy.sol
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/AdminKickPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/BrokerEconomics/BrokerPool.test.ts
packages/network-subgraphs/src/bounty.ts
packages/network-subgraphs/subgraph.yaml

refactor: Bounty events change: BrokerKicked/Slashed separated (all slashings now in BrokerSlashed), avoid solventUntil call in every BountyUpdate

Bounty events change (ETH-468)

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/test/hardhat-slow-tests/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/OperatorFactory.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/OperatorContractOnlyJoinPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/deployOperatorContract.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/setupSponsorships.ts

Idea is that the owner doesn't need to put their private key into a script that manages staking/unstaking/...
also a small unrelated test refactor

feat: Controller role in Operator contract

---

.github/workflows/ci.yaml
packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorFactory.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/OperatorContractOnlyJoinPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/deployOperatorContract.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/deploySponsorshipContract.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/setupSponsorships.ts
packages/network-subgraphs/src/operator.ts

nowadays you can't create Sponsorships without operatorContractsOnly, so removing that option

Small cleanup in tests

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/test/hardhat-slow-tests/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

only useful for tests (not disputing that!), possibly wrong in general. Better to remove and track the total queued in subgraph.
Example when it's wrong:
* queue whole balance
* transfer half balance away
* total queued still is total balance
* smart contract doesn't need this accounting: it will pay out whatever the balance is (or what was requested, which ever is smaller) when the queueing is done

ETH-520: delete Operator.totalQueuedPerDelegatorWei

---

.github/workflows/dependency-review.yaml

`fail-on-severity: low` could be potentially annoying, but I guess we'll just change it if it flags trusted libraries (but if it flags outdated openzeppelin and such, maybe we should consider also updating :)

build: add dependency review to PRs

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

for the case when OperatorValueBreachWatcher calls it
now reward is paid from the withdrawn DATA tokens, so it's not hacky like
the previous solution (where there were no tokens to take from since only
"approximate value" was updated, not token balances, so had to take tokens
from where they were, i.e. pool tokens). Now that earnings are actually
withdrawn, this simplifies the reward payment a lot as well.

ETH-539 OperatorValueBreachWatcher reward refactor

---

packages/network-contracts/contracts/OperatorTokenomics/SponsorshipFactory.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts

it used to give _msgSender() which is wrong: ERC677 should be from whose tokens were used for the initial sponsoring

ETH-549: fix "creator" in the ERC677 sponsorship creation NewSponsorship event

---

packages/config/src/index.ts

Add URL for the `network-subgraph` subgraph. Note that the subgraph has not yet been deployed to production and therefore the `polygon` block doesn't contain a value for the setting. (We have legacy `network-contracts` subgraph in that environment at URL `https://api.thegraph.com/subgraphs/name/streamr-dev/streams`.)

feat(config): add `theGraphUrl`

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

Added comments about why withdrawing is not guarded (it can't harm)
Grouped functions according to caller role

ETH-579: Check Operator contract function guards

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/AdminKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts

Renamed the method to `flag` as all flagging needs to use that method in practice. There was already a `flag` method which didn't have metadata parameter. That method is now removed.
The inspection logic needs that there is partition information available, and we deliver that in the `metadata` field. There are currently no on-chain validations to the metadata. In that sense it is similar to e.g. `StreamRegistry#createStream` which needs the metadata for off-chain use, and validation is implemented off-chain.

refactor: rename `flagWithMetadata`

---

packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol

instead just reduce stake to zero if trying to reduce too much
This case is extremely rare and hard to actually cause; basically if policies commit more stake than the operator has, then _removeOperator might try to _slash more than there is stake. In that case, since it's really "over-slashing" just slash all. It's the responsibility of the policies etc. to make sure there's enough tokens to cover reviewer rewards etc. whatever stake is committed towards.
On the other hand, when capping the slashing to stake, the amount of ACTUAL slashing/reduction must be communicated back, so that the caller doesn't simply assume slashing equals what was requested.

Sponsorship fix: don't let _reduceStakeBy revert when over-slashing

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultUndelegationPolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/QueueModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

Triggered on `operator.undelegate(infinity)`
_handleProfit => _splitEarnings because "earnings" is what comes from Sponsorship, and profit is what remains of it after protocol fee and operator's cut. So really that function splits earnings into those three things.

Fix 100% self-undelegation bug

---

packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultExchangeRatePolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/IExchangeRatePolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/IStakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/QueueModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

...on the happy path at least.
The tests could be simplified too to ignore the operator token, but then again, checking those doesn't hurt

ETH-606: undelegation using DATA, hide operator token from API

---

packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol

especially if the operator token callback would throw, still proceed with removing the operator.

fix: ignore token transfer "return value"

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/IStakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol

refactor: save 24 bytes by moving unstake back to main contract
turns out it costs more to moduleCall it than just add those 2 lines...
also removed "virtual" from the stubs now that we aren't overriding them (using _ in the names instead).

Minor size-optimization while working on ETH-614

---

packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestAllocationPolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestKickPolicy.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/AdminKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/deployOperatorContract.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/deploySponsorshipContract.ts

Organized all Operator tests under describe blocks
Fixed a bug in Sponsorship (kicking and slashing all failed)
deleted one kind of confusing test,
also moved "is not possible to get slashed more than you have staked" to Sponsorship.test.ts,
and fixed up other tests too quite a bit. That kind of snowballed.

Clean up Operator and Sponsorship tests

---

packages/network-contracts/test/hardhat-slow-tests/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/OperatorFactory.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/AdminKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/MaxOperatorsJoinPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/OperatorContractOnlyJoinPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/deployTestContracts.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/setupSponsorships.ts
packages/network-contracts/test/hardhat/Registries/StreamRegistry.test.ts
packages/network-contracts/test/hardhat/Registries/getEIP2771MetaTx.ts

don't mix type and object imports, from "ethers" we only get types; the utils we get from hardhat's version

Clean up tokenomics contract tests' imports

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

this closes the loophole where operator can undelegate freely by transferring their self-delegation to a normal delegator and then undelegating

Activate delegationPolicy and undelegationPolicy in _transfer

---

packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts

Need for this was when "elementary" bugs were found on happy paths

ETH-602: add a longer "scenario" test to Sponsorship

---

packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts

It can now tolerate 1 wei/second type of "absurd" but possible incomePerSecond values.
It can also tolerate 1 wei stake type of cases that are impossible with current minimum stake (decided by flagging+reviewer rewards).

ETH-293: Added numeric precision to StakeWeightedAllocationPolicy

---

packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts

* Move "toplevel-it"s under describe blocks in Operator test
* Use defaultSponsorship in Sponsorship test

Test cleanups

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/IStakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/QueueModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

Hopefully the last feature to get in...
self-delegation is slashed by burning the corresponding amount of operator tokens. So in net, the operator still makes (fee% - reward%) of the earnings. Which I guess is fair. Like with slashing in sponsorships, if the operator has a fee lower than the `fishermanRewardFraction` and managed to get slashed a lot, down to zero, then the fisherman's reward will be on the delegators.
Also other cleanups:
* reverted to msg.sender where appropriate (still left onlyNodes to use _msgSender even though that 100xs the price of heartbeats probably...)
* reverted some stuff from stake module to main contract. StakeModule size went down by a little at the cost of slightly larger Operator contract (note that StakeModule contains the Operator!)
* added comments, …

ETH-636: Take fisherman's reward from self-delegation

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol

refactor: moving functions around
so that Operator and Sponsorship would be a bit more consistent

Final touch-ups of tokenomics contracts

---

packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol

instead of sending StakeUpdate in _slash, make sure all callers (_removeOperator for kick and forceUnstake, _endVote for vote-kick) send both StakeUpdate and SponsorshipUpdate, to avoid multiple emits
SponsorshipUpdate isn't needed in withdraw

fix StakeUpdate and SponsorshipUpdate events

---

packages/hub-contracts/.solhint.json
packages/network-contracts/.solhint.json
packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/QueueModule.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/AdminKickPolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestExchangeRatePolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestExchangeRatePolicy3.sol
packages/network-contracts/selectors.txt
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/OperatorContractOnlyJoinPolicy.test.ts

separate "delegating" from "minting operator tokens". They just aren't the same thing after all: "adding to self-delegation" only concerns the operator and mostly doesn't benefit from the minimum delegation check (or other checks for that matter).

ETH-652: check minimum delegation limit when someone delegates

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol

fix: we shouldn't have any payable functions in the code, since we aren't dealing with ether transfers at all

Remove "payable" from a function

---

packages/network-contracts/contracts/OperatorTokenomics/IERC677Receiver.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorFactory.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipFactory.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/OperatorFactory.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipFactory.test.ts

Sponsorship and Operator contracts already had them.

ETH-666: added missing access checks to onTokenTransfer

---

packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/QueueModule.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

we should support queuing for type(uint).max, and it should just take all tokens

ETH-654: fix very large amount of queued undelegation

---

package-lock.json
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultExchangeRatePolicy.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

…to new and empty operator contract (totalSupply of pooltokens = 0) and then going to undelegation queue

ETH-657 fix division by 0 in queue payment when totalSupply = 0

---

packages/network-contracts/contracts/OperatorTokenomics/Sponsorship.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/AdminKickPolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/IKickPolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestKickPolicy.sol
packages/network-contracts/selectors.txt
packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/StreamrConfig.test.ts
packages/network-contracts/test/integration/contractsSubgraphSmoketest.test.ts
packages/network-subgraphs/schema.graphql
packages/network-subgraphs/src/sponsorship.ts
packages/network-subgraphs/subgraph.yaml
packages/network-subgraphs/subgraph_mumbai.yaml

now it's as good as it's ever been: it takes into account if the operator has been flagged or not, so it only reserves the "flag-target stake" if the flagging hasn't been done yet.
How is this different from just locking flag-target stake for everyone?
* targetStakeAtRiskWei depends on stakedWei at the time of flagging, can't know in advance
* locked stake is forfeited when leaving. If flag hasn't been opened, that stake shouldn't be lost, so it shouldn't be locked either (though of course we could at leaving check if there's a flag, and unlock stake if not. BUT now the main contract doesn't need to know anything about flags!)
it could be ever so slightly more elegant if locking also would completely go into kickpolicy, but then it'd be a bit awkward at the leaving time (removeoperator) …

ETH-686: minimum stake calculation

---

packages/network-contracts/contracts/OperatorTokenomics/StreamrConfig.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/StreamrConfig.test.ts

add events the are emitted when config is changed
separate roles better, don't use DEFAULT_ADMIN_ROLE, so now we can use upgrade to wipe admin privileges by changing the role ID.

ETH-682: centralization risk mitigations

---

.github/workflows/ci.yaml
packages/network-contracts/contracts/OperatorTokenomics/IVoterRegistry.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorFactory.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
packages/network-contracts/contracts/OperatorTokenomics/testcontracts/TestBadOperator.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/OperatorFactory.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/setupSponsorships.ts

feat: VoterRegistry pulls the stakedWei
this way anyone can call the function (msg.sender isn't even checked), so also stale operators can be fixed

ETH-700: Stale operators fix

---

packages/config/src/index.ts

We seem to have a dead RPC in our config list:
https://www.pokt.network/deprecation-of-rpc-endpoints-what-you-need-to-know/

Update polygon RPC

---

packages/docker-dev-chain-init/index.js
packages/network-contracts/scripts/deployToLivenet/1_deployContracts.ts
packages/network-contracts/src/StreamrEnvDeployer.ts

Add `urls` list. In development environment it contains the same info as the deprecated http field (NET-1251), but in production the fields will have different values.
Also removed some unused code related to this functionality.

Add storage node urls to pre-baked image

---

packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/DefaultUndelegationPolicy.sol
packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts

also, the minimum delegation time shouldn't apply to operator themselves.

ETH-748 hotfix: add defenses against streamrConfig address being fubar

---

packages/config/src/index.ts
packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
packages/network-contracts/scripts/2024-05-22-eth-677-reviewer-selection.sh
packages/network-contracts/scripts/upgradeVoteKickPolicy.ts
packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.test.ts

otherwise we pick same reviewers in simultaneous flags in different sponsorships (happens frequently if node went offline)

ETH-774: factor in sponsorship address into reviewer selection

---

packages/ens-sync-script/src/index.ts

this may result on RPC giving error "tip higher than fee cap"

ETH-780: don't let maxPriorityFeePerGas be more than maxFeePerGas

---

packages/network-subgraphs/README.md
packages/network-subgraphs/src/sponsorship.ts

the tokens come from sponsorshipFactory, but that's maybe not a meaningful "sponsor"
TODO: test this against production, i.e. deploy to Studio, then test manually, and if ok, deploy to production.
Query:
```
{
sponsoringEvents(
where: {sponsorship_in: ["0xa5ea814f2f46a5552ed450de93bd87a37fae9881", "0x93ccf5ccb8b56c69b9ee6dbf1da90611cb7dcc0b"]}
) {
amount
sponsor
sponsorship {
id
}
}
}
```
current result:
```
{
"data": {
"sponsoringEvents": [
{
"amount": "150000000000000000000000",
"sponsor": "0xe195aba9b489ac9502cae8fdf3e2d0f3a3a5a255",
"sponsorship": {
"id": "0x93ccf5ccb8b56c69b9ee6dbf1da90611cb7dcc0b"
}
},
{
"amount": "0",
"sponsor": "0x820b2f9a15ed45f9802c59d0cc77c22c81755e45",
"sponsorship": {
"id": "0x93ccf5ccb8b56c69b9ee6dbf1da90611cb7dcc0b"
}
},
{
"amount": …
```

FRONT-1921: for initial sponsorships, set sponsor to be the sponsorship creator

---

packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
packages/network-contracts/test/hardhat/Registries/StreamRegistry.test.ts

Also managed to squeeze in:
* setExpirationTimeForUserId (this is the only setter method that really makes sense: userIds are only supposed to have expiration times)
* grantPermissionForUserId, revokePermissionForUserId

ETH-787: setMultipleStreamPermissionsForUserIds

---

packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
packages/network-contracts/test/hardhat/Registries/StreamRegistry.test.ts

The streamIdToPublicPermissionUserKey wasn't populated. Therefore public permissions vanished after upgrade.
Fixed the issue by removing the function (using normal `getUserKey(streamId, PUBLIC_PERMISSION_USER_ID)`)
Also introduced new `PUBLIC_PERMISSION_USER_ID` constant and using `address(0)` instead of it.

ETH-793: public permissions after upgrade

---

packages/config/src/index.ts

The RPC URL I remove in this PR causes consistent timeouts.
Requests are seen as pending for 30s:
Then turn red immediately after (fallback provider moves on to the next one):

Drop dead Polygon RPC url

---

packages/network-contracts/README.md
packages/network-subgraphs/schema.graphql
packages/network-subgraphs/src/operator.ts
packages/network-subgraphs/tests/integration/event-queue-test.js

Undelegation queue has the "future execution" element: it saves address of the "undelegation requestor" (called `delegator`) and amount. But all checks etc. happen in the payout, that is, when that queue item actually gets processed in `QueueModule._payOutFirstInQueue()`
This means stuff in the queue is allowed to be non-sensical at any given moment before processing: amount can be very large, the delegator not actually a delegator; this is in accordance with the contract logic. The contract is robust to these during payout.
Before this PR the subgraph handling logic assumed that all delegators were real delegators, i.e. this "future execution" assumptions were not taken into account.
Subgraph connects that address to a `Delegator` entity, but there might not exist such `Delegator` …

ETH-802 fix: create dummy `Delegator` entity when non-delegator undelegates

---

.github/workflows/ci.yaml

It seems that these are not needed. Tested in `x86` AWS Linux. CI is green so this is also compatible with that Ubuntu 20.04 version.

test: Remove obsolete Linux x64-specific dependencies

---

.github/workflows/ci.yaml

It is simpler to see the root cause when the tasks are separate steps.

test: Separate `build` and `lint` steps in CI

---

packages/npm-network-contracts/src/exports.ts

Export ABIs as capitalized names, e.g. `StreamRegistryABI` instead of `streamRegistryABI`.
Maybe that naming style is more readable as the ABI is a constant, not a variable. Could have renamed e.g. to `STREAM_REGISTRY_ABI`, but maybe the capitalized version makes most sense as it refers to object instead of an ID.

refactor(npm-network-contracts): Capitalize ABI exports

---

packages/npm-network-contracts/build.sh
packages/npm-network-contracts/hardhat.config.ts
packages/npm-network-contracts/package-lock.json
packages/npm-network-contracts/package.json
packages/npm-network-contracts/src/exports.ts

The `DATAv2` contract implementation is in a separate repo https://github.com/streamr-dev/DATAv2
For end-user convenience it is good that all our contracts are available a single package (`@streamr/network-contracts`)
We added `DataV2` contract as a dependency for  Hardhat `dependencyCompiler`. It causes Hardhat to fetch the npm-published version of the contract and produce build artifacts (ABI and type definitions) locally for that contract.
As a consequence we just needed to add `DATAv2` type and `DATAv2ABI` export definitions to `exports.ts`. 
Ideally we'd just install the `@streamr/data-v2` package and add it to `dependencyCompiler`, but there were problems with dependency versions. `@streamr/data-v2` is compiled with `@openzeppelin/contracts` version 4.0.0, and some dependencies of …

feat(npm-network-contracts): [ETH-859] DATAv2 contract available via `@streamr/network-contracts` package

---

packages/network-subgraphs/start.sh

Poll instead of wait.
Before this change chain startup (`streamr-docker-dev start dev-chain-fast deploy-network-subgraphs-fastchain`) took about 44s, now it takes about 24s.
Could poll also `dev-chain` and `postgres`, but this should also work without those.

chore: Optimize `deploy-network-subgraphs-fastchain` startup

---

packages/network-subgraphs/src/streamRegistry.ts

Fixes problems in subgraph indexing possibly due to very long Permission entity IDs
Use hash for ID instead of the plain streamId + userId

feature(network-subgraphs): [ETH-867] constant-length permission IDs

---

packages/network-subgraphs/README.md
packages/network-subgraphs/src/streamRegistry.ts

* add streamId back to StreamPermission.id (although only the first 1k characters)
* this solves two problems:
* ETH-867 bug with overlong StreamPermission.id
* NET-1461 bug with ordering/pagination problems in shipped StreamrClients
Once overlong streamId problem is solved, we can remove the slicing (without risking re-introducing ETH-867).

feature(network-subgraphs): [ETH-875] Add stream IDs back to permission IDs in subgraph on IDs in subgraph

---

packages/network-subgraphs/src/helpers.ts
packages/network-subgraphs/src/projectRegistry.ts
packages/network-subgraphs/src/sponsorshipFactory.ts
packages/network-subgraphs/src/streamRegistry.ts
packages/network-subgraphs/src/streamStorageRegistry.ts

Added stream ID length check to all events handlers which process stream related events. If the stream ID is more than 1000 characters, the event is just ignored. That causes the stream to be fully ignored in The Graph (it won't appear e.g. in the `streams` query).
We need to document to our public document that overlong streams are not supported (i.e. the behavior is undefined in our system for those streams).
```bash
PRIVATE_KEY="1111111111111111111111111111111111111111111111111111111111111111"
NOW=$(date +%Y%m%d%H%M%S)
LONG_SNIPPET=$(printf 'a%.0s' {1..2000})
echo 'Create streams'
npx tsx bin/streamr.ts internal token-mint self 1000000 1000000 --env dev2 --private-key $PRIVATE_KEY
npx tsx bin/streamr.ts stream create /short1-$NOW --env dev2 --private-key $PRIVATE_KEY
npx tsx …
```

fix(network-subgraphs): [ETH-876] Ignore overlong stream ids

---

packages/network-subgraphs/schema.graphql
packages/network-subgraphs/src/streamRegistry.ts

Added new field to `Stream` entity: `Stream#idAsString`. It has same value as in the `id` field. The field allows us do to substring queries for the field id (by using `idAsString_contains` where clause).
This feature is needed e.g. in https://github.com/streamr-dev/network/pull/3132.

feat(network-subgraphs): Add `idAsString` field

---

packages/network-subgraphs/schema.graphql

Annotated the field as non-nullable in the GraphQL schema. The argument type for the field is `uint` in the `SponsorshipFactory#deploySponsorship`, and therefore it can't hold `null` value:
```solidity
function deploySponsorship(
uint minOperatorCount,
string calldata streamId,
string calldata metadata,
address[] calldata policies,
uint[] calldata policyParams
)
```

chore(network-subgraphs): `Sponsorship#minOperators` is not nullable

---

.github/workflows/ci.yaml
README.md
packages/config/package.json

Changed main branch to be `main` instead of `master`. It is the new standard. After this PR we can use some tools which assume the main branch name to be `main`.
- CI config
- URLs to files in GitHub repo
- `git branch -m master main`
- `git push -u origin main`
- configure main branch in GitHub settings
- `git push origin --delete master`

chore: Main branch name

---

.github/workflows/ci.yaml

Upgaded the action from v3 to v4.
The upgrade fixes a warning, which was shown in GitHub actions UI:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

chore: Use `actions/checkout@v4` in `ci.yaml`

---

packages/network-subgraphs/src/streamRegistry.ts

Updated the comment. It mentioned slicing which we removed in https://github.com/streamr-dev/network-contracts/pull/993.

docs(network-subgraphs): Update comment about `getPermissionId()`

---

packages/network-contracts/tsconfig.json
packages/network-contracts/types/hardhat-type-extensions.d.ts

Added an explicit type definition files for Hardhat. For some reason Hardhat doesn't find the correct type information without this file. See comments of `hardhat-type-extensions.d.ts` for details.

chore(network-contracts): [ETH-899] Add Hardhat type definitions

---

package-lock.json
package.json
packages/dev-chain-fast/package.json
packages/ens-sync-script/package.json
packages/network-contracts/package.json

Added missing `node-fetch` dependency to the `network-subgraph` subpackage.

chore: [ETH-904] Bump `typescript` to v5.8.3
